personal/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list_persons$', views.PersonList.as_view(), name='person_list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetail.as_view(), name="person_detail"),
    url(r'^person/new', views.PersonCreation.as_view(), name="new_person"),
]

resourcestock/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^list_resources$', views.ResourceStockList.as_view(), name='resource_list'),
    url(r'^resource/new', views.ResourceStockCreation.as_view(), name="new_resource"),
    url(r'^resource/(?P<pk>[0-9]+)/$', views.ResourceStockDetail.as_view(), name="resource_detail"),

    url(r'^list_assignment$', views.ResourcesAssignmentList.as_view(), name='assignment_list'),
    url(r'^assignment/new', views.ResourcesAssignmentCreation.as_view(), name="new_assignment"),

    url(r'^search_assignments$', views.search_assignment, name='search_assignment'),
    url(r'^search_assignments/(?P<idPerson>[0-9]+)/$', views.search_assignment, name='search_assignment'),

    url(r'^move_assignment$', views.move_assignment, name='move_assignment'),
    url(r'^move_assignment/(?P<idAssignment>[0-9]+)/$', views.move_assignment, name='move_assignment'),
]

stocktaking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('personal.urls', namespace='personal')),
    url(r'^', include('resourcestock.urls', namespace='resourcestock')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/models.py
# -*-coding:utf-8-*-
from __future__ import unicode_literals

from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self):
        return ('%s %s' % (self.first_name, self.last_name))

    class Meta:
        ordering = ('last_name', )

personal/forms.py
from django import forms
from .models import Person

personal/views.py
# -*-coding:utf-8-*-
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from .models import Person
from resourcestock.models import ResourceStock

class PersonList(ListView):
    model = Person

class PersonDetail(DetailView):
    model = Person

class PersonCreation(CreateView):
    model = Person
    success_url = reverse_lazy('personal:person_list')
    fields = '__all__'

templates/personal/person_detail.html
{% extends "base.html" %}
{% block site_title %}
  Details from {{ person.first_name }} {{ person.last_name }}
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'personal:person_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h3>First Name:</h3>
      {{ person.first_name }}
      <h3>Last Name:</h3>
      {{ person.last_name }}
    </div>
  </div>
{% endblock %}

templates/personal/person_form.html
{% extends "base.html" %}
{% block site_title %}
  Stock | New Person
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'personal:person_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">New Person</h2>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/personal/person_list.html
{% extends "base.html" %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Persons</h2>
      <a class="btn btn-primary" href="{% url 'personal:new_person' %}" role="button">
        New Person
      </a>
      <ul>
          {% for p in object_list %}
              <li>
                  <a class="badge" href="{% url 'personal:person_detail' pk=p.id %}">Ver +</a>
                  {{ p.first_name }} {{ p.last_name }}
              </li>
          {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}