personal/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list_persons$', views.PersonList.as_view(), name='person_list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetail.as_view(), name="person_detail"),
    url(r'^person/new', views.PersonCreation.as_view(), name="new_person"),
]

resourcestock/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^list_resources$', views.ResourceStockList.as_view(), name='resource_list'),
    url(r'^resource/new', views.ResourceStockCreation.as_view(), name="new_resource"),
    url(r'^resource/(?P<pk>[0-9]+)/$', views.ResourceStockDetail.as_view(), name="resource_detail"),

    url(r'^list_assignment$', views.ResourcesAssignmentList.as_view(), name='assignment_list'),
    url(r'^assignment/new', views.ResourcesAssignmentCreation.as_view(), name="new_assignment"),

    url(r'^search_assignments$', views.search_assignment, name='search_assignment'),
    url(r'^search_assignments/(?P<idPerson>[0-9]+)/$', views.search_assignment, name='search_assignment'),

    url(r'^move_assignment$', views.move_assignment, name='move_assignment'),
    url(r'^move_assignment/(?P<idAssignment>[0-9]+)/$', views.move_assignment, name='move_assignment'),
]

stocktaking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('personal.urls', namespace='personal')),
    url(r'^', include('resourcestock.urls', namespace='resourcestock')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <link rel="icon" type="image/png" href="img/favicon.ico">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <title>{% block site_title %}My Warehouse{% endblock %}</title>
    <meta content="Diana Hernandez" name="author" />

    <!-- Bootstrap core CSS     -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" />
    <!-- Animation library for notifications   -->
    <link href="{{STATIC_URL}}css/animate.min.css" rel="stylesheet"/>
    <!--  Light Bootstrap Table core CSS    -->
    <link href="{{STATIC_URL}}css/light-bootstrap-dashboard.css" rel="stylesheet"/>
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{{STATIC_URL}}css/pe-icon-7-stroke.css" rel="stylesheet" />

    <link href="{{STATIC_URL}}css/select2.min.css" rel="stylesheet" id="select2" />
    <script src="{{STATIC_URL}}js/jquery-3.2.1.min.js"></script>
  </head>
  <body>

    <header>
      {% block site_header %}
      <h1>My Warehouse</h1>
      {% endblock %}
    </header>
    <section>
      {% block content %}{% endblock %}
    </section>
    <footer>
      {% block site_footer %}{% endblock %}
    </footer>

    <script type="text/javascript">base = "{{STATIC_URL}}"</script>
    <!-- Select2 -->
    <script src="{{STATIC_URL}}js/select2.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        $("select.one").select2();
        $("select.many").select2({
          multiple:true
        });
      });
    </script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Persons</h3>
      <a class="btn btn-primary" href="{% url 'personal:person_list' %}" role="button">
        Admin Persons
      </a>
      <ul>
        <li>List Persons</li>
        <li>New Person</li>
        <li>Detail Person</li>
      </ul>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Resources</h3>
      <a class="btn btn-primary" href="{% url 'resourcestock:resource_list' %}" role="button">
        Admin Resources
      </a>
      <ul>
        <li>List Resources</li>
        <li>New Resource</li>
        <li>Detail Resource</li>
      </ul>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Resources Assignment</h3>
      <a class="btn btn-primary" href="{% url 'resourcestock:assignment_list' %}" role="button">
        Admin Resources Assignment
      </a>
      <ul>
        <li>Assign resources to person</li>
        <li>Move one or many resources from one person to another</li>
        <li>Assignments to a person</li>
        <li>Resources history assignment</li>
      </ul>
    </div>
  </div>

{% endblock %}