personal/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list_persons$', views.PersonList.as_view(), name='person_list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetail.as_view(), name="person_detail"),
    url(r'^person/new', views.PersonCreation.as_view(), name="new_person"),
]

resourcestock/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^list_resources$', views.ResourceStockList.as_view(), name='resource_list'),
    url(r'^resource/new', views.ResourceStockCreation.as_view(), name="new_resource"),
    url(r'^resource/(?P<pk>[0-9]+)/$', views.ResourceStockDetail.as_view(), name="resource_detail"),

    url(r'^list_assignment$', views.ResourcesAssignmentList.as_view(), name='assignment_list'),
    url(r'^assignment/new', views.ResourcesAssignmentCreation.as_view(), name="new_assignment"),

    url(r'^search_assignments$', views.search_assignment, name='search_assignment'),
    url(r'^search_assignments/(?P<idPerson>[0-9]+)/$', views.search_assignment, name='search_assignment'),

    url(r'^move_assignment$', views.move_assignment, name='move_assignment'),
    url(r'^move_assignment/(?P<idAssignment>[0-9]+)/$', views.move_assignment, name='move_assignment'),
]

stocktaking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('personal.urls', namespace='personal')),
    url(r'^', include('resourcestock.urls', namespace='resourcestock')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resourcestock/models.py
# -*-coding:utf-8-*-
from __future__ import unicode_literals

from django.db import models
from personal.models import Person

class ResourceStock(models.Model):
    category = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)

    def __str__(self):
        return (self.name)

    class Meta:
        ordering = ('name', )

class ResourcesAssignment(models.Model):
    person_warehouse = models.ForeignKey(Person)
    resource_warehouse = models.ForeignKey(ResourceStock)
    date_assignment = models.DateTimeField(auto_now_add=True, blank=True)
    assigned = models.BooleanField(default=True)

    def __str__(self):
        return ('%s - %s %s' % (self.resource_warehouse.name, self.person_warehouse.first_name, self.person_warehouse.last_name))

    class Meta:
        ordering = ('date_assignment', )

resourcestock/forms.py
from django import forms
from .models import ResourceStock, ResourcesAssignment
from personal.models import Person

def adicionarClase(campo, clase):
    campo.widget.attrs.update({'class': clase})
    return campo

class SearchPersonForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SearchPersonForm, self).__init__(*args, **kwargs)
        self.fields['person'] = adicionarClase(self.fields['person'], 'one')

    person = forms.ModelChoiceField(required=True, queryset=Person.objects.all(), widget=forms.Select(attrs={'size': '6', 'readonly': True}))

class MovePersonForm(forms.Form):
    person = forms.ModelChoiceField(required=True, queryset=None)

    def __init__(self, *args, **kwargs):
        self.id_asignado = kwargs.pop('id')
        super(MovePersonForm, self).__init__(*args, **kwargs)

        old_p = ResourcesAssignment.objects.get(id=self.id_asignado).person_warehouse
        self.fields['person'].queryset = Person.objects.all().exclude(id=old_p.id)
        self.fields['person'] = adicionarClase(self.fields['person'], 'one')

class ResourcesAssignmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ResourcesAssignmentForm, self).__init__(*args, **kwargs)
        self.fields['person_warehouse'] = adicionarClase(self.fields['person_warehouse'], 'one')
        self.fields['resource_warehouse'] = adicionarClase(self.fields['resource_warehouse'], 'one')

        assignment_resources = ResourcesAssignment.objects.all()
        id_assigned_resources = []
        for i in assignment_resources:
            id_assigned_resources.append(i.resource_warehouse.id)
        visibles_resources = ResourceStock.objects.exclude(id__in=id_assigned_resources)

        self.fields['resource_warehouse'].queryset = visibles_resources

    class Meta:
        model = ResourcesAssignment
        fields = ['person_warehouse', 'resource_warehouse']

resourcestock/views.py
# -*-coding:utf-8-*-
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect
from .models import ResourceStock, ResourcesAssignment
from django.apps import apps
from .forms import SearchPersonForm, ResourcesAssignmentForm, MovePersonForm, Person
from datetime import datetime

# Index
def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))

# Resources
class ResourceStockList(ListView):
    model = ResourceStock

class ResourceStockDetail(DetailView):
    model = ResourceStock

class ResourceStockCreation(CreateView):
    model = ResourceStock
    success_url = reverse_lazy('resourcestock:resource_list')
    fields = '__all__'

# ResourcesAssignment
class ResourcesAssignmentList(ListView):
    model = ResourcesAssignment
    queryset = ResourcesAssignment.objects.order_by('-date_assignment')

class ResourcesAssignmentCreation(CreateView):
    model = ResourcesAssignment
    form_class = ResourcesAssignmentForm
    success_url = reverse_lazy('resourcestock:assignment_list')

def search_assignment(request, idPerson=None):
    person = None
    assignment_list = []
    try:
        person = Person.objects.get(id=idPerson)
    except Exception as e:
        pass

    if request.method == 'POST':
        form = SearchPersonForm(request.POST)
        if form.is_valid():
            person = form.cleaned_data['person']
            return redirect("resourcestock:search_assignment", person.id)

    if person:
        form = SearchPersonForm({'person': person.id})
        assignment_list = ResourcesAssignment.objects.filter(person_warehouse=person, assigned=True)
    else:
        form = SearchPersonForm()

    template = loader.get_template('resourcestock/search_assignments.html')
    context = {
        'form': form,
        'person': person,
        'assignment_list': assignment_list,
    }
    return HttpResponse(template.render(context, request))

def move_assignment(request, idAssignment=None):
    assignment = None
    try:
        assignment = ResourcesAssignment.objects.get(id=idAssignment)
    except Exception as e:
        pass
    if request.method == 'POST':
        form = MovePersonForm(request.POST, id=idAssignment)
        if form.is_valid():
            # Actual Registro
            personId = assignment.person_warehouse.id
            assignment.assigned = False
            assignment.save()
            # Nuevo Registro
            fecha_hora_actual = datetime.now()
            new_person = form.cleaned_data['person']
            new_assignment = ResourcesAssignment(
                person_warehouse=new_person,
                resource_warehouse=assignment.resource_warehouse,
                date_assignment=fecha_hora_actual,
                assigned=True,
            )
            new_assignment.save()
            return redirect("resourcestock:search_assignment", personId)
    else:
        form = MovePersonForm(id=idAssignment)

    template = loader.get_template('resourcestock/move_assignment.html')
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))

templates/resourcestock/move_assignment.html
{% extends "base.html" %}
{% block site_title %}
  Stock | Move Assignment
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'resourcestock:assignment_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Move Resources Assignment</h2>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Move</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/resourcestock/resourcesassignment_form.html
{% extends "base.html" %}
{% block site_title %}
  Stock | New Resource
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'resourcestock:assignment_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">New Assignment Resource</h2>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/resourcestock/resourcesassignment_list.html
{% extends "base.html" %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Resources Assignment</h2>

      <h4>Assign resources to person</h4>
      Click <a class="badge" href="{% url 'resourcestock:new_assignment' %}">here</a>

      <h4>Move one or many resources from one person to another</h4>
      <h5>Consult assignments to a person</h5>
      Click <a class="badge" href="{% url 'resourcestock:search_assignment' %}">here</a>

      <h4>Resources history assignment</h4>
      <table class="table">
        <thead>
          <tr>
            <th>Resource</th>
            <th>Person</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {% for p in object_list %}
          <tr>
            <td>{{ p.resource_warehouse.name }}</td>
            <td>{{ p.person_warehouse.first_name }} {{ p.person_warehouse.last_name }}</td>
            <td>{{ p.date_assignment }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

templates/resourcestock/resourcestock_detail.html
{% extends "base.html" %}
{% block site_title %}
  Details from {{ resourcestock.name }}
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'resourcestock:resource_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h3>Category:</h3>
      {{ resourcestock.category }}
      <h3>Code:</h3>
      {{ resourcestock.code }}
      <h3>Name:</h3>
      {{ resourcestock.name }}
      <h3>Brand:</h3>
      {{ resourcestock.brand }}
    </div>
  </div>
{% endblock %}

templates/resourcestock/resourcestock_form.html
{% extends "base.html" %}
{% block site_title %}
  Stock | New Resource
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'resourcestock:resource_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">New Resource</h2>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/resourcestock/resourcestock_list.html
{% extends "base.html" %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Resources</h2>
      <a class="btn btn-primary" href="{% url 'resourcestock:new_resource' %}" role="button">
        New Resource
      </a>
      <ul>
          {% for p in object_list %}
              <li>
                  <a class="badge" href="{% url 'resourcestock:resource_detail' pk=p.id %}">{{ p.code }}</a>
                  {{ p.name }} ({{ p.brand }})
              </li>
          {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

templates/resourcestock/search_assignments.html
{% extends "base.html" %}
{% block site_title %}
  Stock | Search Assignment
{% endblock %}

{% block site_header %}
<h1>My Warehouse</h1>
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'resourcestock:index' %}" role="button">
    Index
  </a>
  <a class="btn btn-primary" href="{% url 'resourcestock:assignment_list' %}" role="button">
    Back
  </a>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Search Resources Assignment</h2>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>

  {% if assignment_list %}
  <div class="card">
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>Resource</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for row in assignment_list %}
          <tr>
            <td>{{row.resource_warehouse}}</td>
            <td>{{row.date_assignment}}</td>
            <td>
              <a href="{% url 'resourcestock:move_assignment' row.id %}">
  							<button class="btn btn-primary">Move</button>
  						</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}

{% endblock %}